### ISSUE TITLE
Test Routine Failed

### ISSUE THREAD

**Issue by joergheintz** [browarsoftware/RMoCap#1]
Hi, 

I followed the instructions given here https://github.com/browarsoftware/RMoCap
and got the following error message. 

plot(right.arm.motion.1, frames.fraction = 0.5, my.color = "white", alpha = 1, spheres = FALSE)
Error in xy.coords(x, y, xlabel, ylabel, log) :  **'x' is a list, but does not have components 'x' and 'y'**

Since right.arm.motion.1 is a list, I need to determine the x, y variables with something like this "right.arm.motion.1$Skeleton$x" 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/7429472/82154866-6944e480-9836-11ea-84c4-7133891db14e.png">

Thanks for your help.

**Comment by browarsoftware** [comment]
I cannot reproduce the error. xy.coords is a core R function. Try to run:

library("RMoCap")
data("right.arm.motion.1")
library(rgl)
rgl.open()
print.frame(right.arm.motion.1, frame = 1, my.color = "green", alpha = 1, spheres = FALSE, df = NULL, print.text = FALSE)

and please report me the resutls.

**Comment by joergheintz** [comment]
I had to install XQuartz before I could run your suggestion.

Session info below.

see screen recording attached.

Thank you for your help.


[cid:image001.png@01D62C54.6D7F42A0]







George Heintz
Program Manager Health Data Analytics Initiative

The Grainger College of Engineering
Health Care Engineering Systems Center (HCESC)
1206 W. Clark Street, Room 2109 CSL Studio
(217)-300-1924
healtheng.illinois.edu<https://urldefense.proofpoint.com/v2/url?u=https-3A__healtheng.illinois.edu_&d=DwMGaQ&c=Y6HT0gyZH_Z4ZSRJdNYJeQ&r=DEKtmbVzkBavbaVvenBXn9KNIMj2X4R_pSDgl1-7UHs&m=3vyeTYgA9cu9uFYBXoFCtFxSxWq8FN6z4ZdQBtwfj1w&s=YIr_MOtBDADy8DVGuMNM4UrdkYwoM3EOOTdjqbJKH9Q&e=>

[signature_713033781]

**Comment by browarsoftware** [comment]
I do not see any attachemnt, please upload it directly to Github. It seems like a problem with RGL library. Do you use Mac OS?

**Comment by joergheintz** [comment]
https://www.youtube.com/watch?v=VlIpI2nNXQA


<img width="954" alt="image" src="https://user-images.githubusercontent.com/7429472/82158354-f1ce7f80-984c-11ea-9bf3-50b660f1e08c.png">

**Comment by browarsoftware** [comment]
Try run:
plot.mocap(right.arm.motion.1, frame = 1, my.color = "white", alpha = 1, spheres = TRUE)

it seems that instead of running override method R calls deafault one.

**Comment by joergheintz** [comment]
The "right arm movement" is difficult to see .... 

https://www.youtube.com/watch?v=0zqy6j6enpI&feature=youtu.be

**Comment by joergheintz** [comment]
https://www.youtube.com/watch?v=0zqy6j6enpI&feature=youtu.be



George Heintz
Program Manager Health Data Analytics Initiative

The Grainger College of Engineering
Health Care Engineering Systems Center (HCESC)
1206 W. Clark Street, Room 2109 CSL Studio
(217)-300-1924
healtheng.illinois.edu<https://urldefense.proofpoint.com/v2/url?u=https-3A__healtheng.illinois.edu_&d=DwMGaQ&c=Y6HT0gyZH_Z4ZSRJdNYJeQ&r=DEKtmbVzkBavbaVvenBXn9KNIMj2X4R_pSDgl1-7UHs&m=3vyeTYgA9cu9uFYBXoFCtFxSxWq8FN6z4ZdQBtwfj1w&s=YIr_MOtBDADy8DVGuMNM4UrdkYwoM3EOOTdjqbJKH9Q&e=>

[signature_713033781]

**Comment by browarsoftware** [comment]
Then Run
plot.mocap(right.arm.motion.1, frames.fraction = 0.5, my.color = "white", alpha = 1, spheres = FALSE)

:-)
It seems that your R install does not recognize tha S3 class mocap. It is correctly loaded, however instead of running plot.mocap it runs plot.default.
It seems to me an R issue, not the library. You should run:
plot.mocap anytime you want to plot mocap class.

**Comment by joergheintz** [comment]
thanks much …



George Heintz
Program Manager Health Data Analytics Initiative

The Grainger College of Engineering
Health Care Engineering Systems Center (HCESC)
1206 W. Clark Street, Room 2109 CSL Studio
(217)-300-1924
healtheng.illinois.edu<https://urldefense.proofpoint.com/v2/url?u=https-3A__healtheng.illinois.edu_&d=DwMGaQ&c=Y6HT0gyZH_Z4ZSRJdNYJeQ&r=DEKtmbVzkBavbaVvenBXn9KNIMj2X4R_pSDgl1-7UHs&m=3vyeTYgA9cu9uFYBXoFCtFxSxWq8FN6z4ZdQBtwfj1w&s=YIr_MOtBDADy8DVGuMNM4UrdkYwoM3EOOTdjqbJKH9Q&e=>

[signature_713033781]
